import React from 'react';
import {Image,Pressable,SafeAreaView,ScrollView,StatusBar,Text,View} from 'react-native';

export default function HomeScreen({s,darkMode,contentWidth,tabletPage,tablet,homeCardWidth,refreshControl,setScreen,setTxDate}){
 return <SafeAreaView style={[s.safe,darkMode&&s.darkSafe]}><View style={[s.responsiveShell,{width:contentWidth}]}><StatusBar barStyle={darkMode?'light-content':'dark-content'}/><ScrollView refreshControl={refreshControl} contentContainerStyle={[s.landingPage,darkMode&&s.darkPage,tabletPage]}><View style={s.landingHeader}><Image source={{uri:'/app-icon.png'}} style={s.piggyLogo}/><View style={{flex:1}}><Text style={s.landingTitle}>My Personal Budgeting</Text><Text style={s.landingSub}>Plan today. A brighter tomorrow.</Text></View><Pressable onPress={()=>setScreen('settings')}><Text style={s.settingsIcon}>⚙</Text></Pressable></View><View style={{marginHorizontal:10,marginTop:4,marginBottom:2}}><Text style={s.hello}>{new Date().getHours()<12?'Good Morning':new Date().getHours()<17?'Good Afternoon':'Good Evening'}, Vinodhkumar!</Text><Text style={s.question}>What would you like to do today?</Text></View><View style={{flexDirection:'row',flexWrap:'wrap',justifyContent:'space-between',rowGap:14,columnGap:14,marginHorizontal:10}}>
 <Pressable onPress={()=>setScreen('directDebits')} style={({pressed})=>[s.activeLandingCard,{width:homeCardWidth,minHeight:tablet?126:150,borderRadius:18,padding:tablet?14:16,backgroundColor:'#dbeeff'},pressed&&{opacity:.8}]}><Text style={{fontSize:tablet?34:42}}>📅</Text><Text style={s.landingCardTitle}>Direct Debits</Text><Text style={s.landingCardSub}>Manage your monthly payments</Text></Pressable>
 <Pressable onPress={()=>{setTxDate(null);setScreen('incomeExpenses')}} style={({pressed})=>[{width:homeCardWidth,minHeight:tablet?126:150,borderRadius:18,padding:tablet?14:16,backgroundColor:'#ffe0e7'},pressed&&{opacity:.8}]}><Text style={{fontSize:tablet?34:42}}>🐷</Text><Text style={s.landingCardTitle}>Weekly Expense</Text><Text style={s.landingCardSub}>Track weekly credit card spending</Text></Pressable>
 <Pressable onPress={()=>setScreen('savings')} style={{width:homeCardWidth,minHeight:tablet?126:150,borderRadius:18,padding:tablet?14:16,backgroundColor:'#ddf6e4'}}><Text style={{fontSize:tablet?34:42}}>🌱</Text><Text style={s.landingCardTitle}>Savings</Text><Text style={s.landingCardSub}>Grow your future</Text></Pressable>
 <View style={{width:homeCardWidth,minHeight:tablet?126:150,borderRadius:18,padding:tablet?14:16,backgroundColor:'#e7ddff'}}><Text style={{fontSize:tablet?34:42}}>🏠</Text><Text style={s.landingCardTitle}>Mortgage</Text><Text style={s.landingCardSub}>View your mortgage details</Text></View>
 <Pressable onPress={()=>setScreen('incomeOutgoings')} style={{width:homeCardWidth,minHeight:tablet?126:150,borderRadius:18,padding:tablet?14:16,backgroundColor:'#ffedc7'}}><Text style={{fontSize:tablet?34:42}}>💷</Text><Text style={s.landingCardTitle}>Income & Outgoings</Text><Text style={s.landingCardSub}>See how your salary is split</Text></Pressable>
 <Pressable onPress={()=>setScreen('monthlyCalculation')} style={{width:homeCardWidth,minHeight:tablet?126:150,borderRadius:18,padding:tablet?14:16,backgroundColor:'#d6f4f3'}}><Text style={{fontSize:tablet?34:42}}>🧮</Text><Text style={s.landingCardTitle}>Monthly Calculation</Text><Text style={s.landingCardSub}>Income, expenses and breakdown</Text></Pressable>
 </View><View style={s.quoteCard}><Text style={s.quote}>🌱  “Small steps make big progress.”</Text></View></ScrollView></View></SafeAreaView>;
}
